import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import BuyNowButton from "../components/buy-now-button/BuyNowButton.component";
import ConnectWallet from "../components/connect-wallet/ConnectWallet.component";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.main}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className={styles.header}>
        <nav className={styles.nav}>
          <ConnectWallet />
        </nav>
      </header>
      <main className={styles.container}>
        <div className={styles.row}>
          <div className={styles.col}>
            <div className={styles.nftCard}>
              <div className={styles.nftCardImage}>
                <Image src={"/azuki-1.png"} width={320} height={280} />
              </div>
              <div className={styles.nftCardBody}>
                <h2>Azuki#001</h2>
                <p>
                  Lorem ipsum dolor, sit amet consectetur adipisicing elit. Et
                  doloribus nam corporis, unde maxime in quis sapiente esse
                  totam aliquam temporibus.
                </p>
                <BuyNowButton amount={10} />
              </div>
            </div>
          </div>
          <div className={styles.col}>
            <div className={styles.nftCard}>
              <div className={styles.nftCardImage}>
                <Image src={"/azuki-2.png"} width={320} height={280} />
              </div>
              <div className={styles.nftCardBody}>
                <h2>Azuki#002</h2>
                <p>
                  Lorem ipsum dolor, sit amet consectetur adipisicing elit. Et
                  doloribus nam corporis, unde maxime in quis sapiente esse
                  totam aliquam temporibus.
                </p>
                <BuyNowButton amount={20} />
              </div>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
};

export default Home;
